language: ruby

rvm:
  - 2.2

python:
  - 2.7

before_install:
  - sudo apt-get -y update

before_script:
  - gem install awesome_bot
  - sudo apt-get install python-pip python-dev build-essential
  - sudo pip install pykwalify

script:
  - pykwalify --data-file games.yaml --schema-file schema.yaml
  - awesome_bot README.md --allow-redirect --allow-ssl

notifications:
  email:
    recipients:
      - estetus+travis-ci@gmail.com
    on_success: change
    on_failure: always
